### ISSUE TITLE
Extract the calculated Height 

### ISSUE THREAD

**Issue by d3fkon** [vivaxy/react-native-auto-height-image#1]
I'll be happy if you can implement a way to use the calculated height value. It will save us a lot of time to make modals for viewing photos.

**Comment by vivaxy** [comment]
PR is welcomed.

**Comment by vivaxy** [comment]
Here is my implement: https://github.com/vivaxy/react-native-auto-height-image/pull/2

**Comment by vivaxy** [comment]
v0.3.0 released.
https://github.com/vivaxy/react-native-auto-height-image/compare/v0.2.2...v0.3.0
