### ISSUE TITLE
Event Success

### ISSUE THREAD

**Issue by jvitorr** [vivaxy/react-native-auto-height-image#13]
Hello, 

There is a event when Image is loaded ?

**Comment by vivaxy** [comment]
@jvitorr You can use `onLoad`, `onLoadStart` and `onLoadEnd` event handler.
The results of those events are handled by react-native `Image`. `react-native-auto-height-image` loads image at the mean time using `Image.getSize` api. `Image.getSize` result only affects `onError` event handler.
If you have further more questions, feel free to ask here.

**Comment by mak12** [comment]
@vivaxy still not clear though how one can achieve if image is loaded or not? Any help or snipet will be appreciated.

**Comment by tombailey** [comment]
@mak12 just set onLoadEnd and onError props on your react-native-auto-height-image component. Any extra props get passed down to the underyling React Native Image:

https://github.com/vivaxy/react-native-auto-height-image/blob/master/autoHeightImage.js#L92
