### ISSUE TITLE
React-Native 0.56.0: Trailing comma in element is causing bundle error

### ISSUE THREAD

**Issue by ddcrobert** [vivaxy/react-native-auto-height-image#15]
Issue is quite similar to [https://github.com/mjsolidarios/react-native-search-filter/issues/16](https://github.com/mjsolidarios/react-native-search-filter/issues/16).

Bundling with React-Native 0.56.0 leads to this error:
> error: bundling failed: SyntaxError: ... node_modules/react-native-auto-height-image/autoHeightImageWithErrorFallback.js: A trailing comma is not permitted after the rest element (19:24)

        const {
            source,
            fallbackSource,
            onError,
            ...restProps,
        } = this.props;

Oh, I just saw its fixed on master. Would be cool if you could push an 1.0.1 with this fix.

**Comment by vivaxy** [comment]
Thanks for reporting.

Fixed by commit: https://github.com/vivaxy/react-native-auto-height-image/commit/e3c011c6f45189d36648c0391b2e7e7284cb2f46

Released v1.0.1
