### ISSUE TITLE
"A trailing comma is not permitted after the rest element" error

### ISSUE THREAD

**Issue by tombuyse** [vivaxy/react-native-auto-height-image#17]
I'm receiving this error when updating to React native 0.57.

Project dependencies:
React Native 0.57
React 16.5
React-native-auto-height-image 1.0.1

Any idea what is causing this exactly?

**Comment by vivaxy** [comment]
react-native-auto-height-image@1.0.1 has already remove the trailing comma after the rest element.
Please provide detailed error stack.

**Comment by tombuyse** [comment]
Removed the node_modules and reinstalled. Seems to work fine now.

Thanks for the quick response!
