### ISSUE TITLE
ComponentWillReceiveProps is depreciated and will be removed in the next major react native version.

### ISSUE THREAD

**Issue by amrlabib** [vivaxy/react-native-auto-height-image#36]
**Describe the bug**

`ComponentWillReceiveProps` is depreciated and will be removed in the next major react native version.

**Expected behavior**

Update library code to use `getDerivedStateFromProps`

**Dependencies versions (please complete the following information):**
 - react: 16.8.6
 - react-native: 0.60.5

**Comment by vivaxy** [comment]
Fixed by @alexnaiman in #38. Released v1.1.2.
