### ISSUE TITLE
componentWillReceiveProps is deprecated (in dependency)

### ISSUE THREAD

**Issue by r3dm1ke** [vivaxy/react-native-auto-height-image#41]
**Describe the bug**
Right now, there is this warning on every mounting:
```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
```
This is happening b/c `react-native-image-polyfill` is using it. I looked at its repo, looks like it is abandoned for a while. I suggest either getting rid of this dependency or incorporating its code into the codebase and fixing ourselves. If that is something you are ok with, I can work on a PR.

**Comment by vivaxy** [comment]
Thank you for your remind. PR is welcomed.

And there are some other choices.
1. Issue https://github.com/robinpowered/react-native-android-image-polyfill/issues/3 has been created to the repo.
2. Maybe cooperate with https://github.com/LasseSLambertsen/react-native-auto-height-image. https://github.com/LasseSLambertsen had done a lot by making react-native-auto-height-image using react hooks.
