### ISSUE TITLE
Height doesn't change. Same behaviour as Image

### ISSUE THREAD

**Issue by ADjenkov** [vivaxy/react-native-auto-height-image#46]
It seems that height is not changed, testing on iOS simulator, and still the same extra height is calculated

![image](https://user-images.githubusercontent.com/5860190/78215131-7e042d80-74bf-11ea-928d-a574e0706907.png)

The blue background is  backgroundColor: 'blue' to the <AutoHeightImage>

Using as follows:
```              
<AutoHeightImage
                resizeMethod="resize"
                resizeMode="contain"
                style={styles.postContentImage}
                source={{ uri: itemImageUrl }}>
</AutoHeightImage>
```

**Comment by vivaxy** [comment]
@ADjenkov Cannot reproduce. Please provide an example.

**Comment by ADjenkov** [comment]
Sorry, It was a problem in my 'TV' 
It works just perfect!
