### ISSUE TITLE
Required animated attribute

### ISSUE THREAD

**Issue by sa1dai** [vivaxy/react-native-auto-height-image#49]
![screenshot_93](https://user-images.githubusercontent.com/47157550/79590048-1664f980-80df-11ea-9dac-68158cf95c44.png)
![screenshot_94](https://user-images.githubusercontent.com/47157550/79590065-1f55cb00-80df-11ea-9d49-733e983235ab.png)

Missing '?' symbol?

**Comment by sa1dai** [comment]
By the way, width="100%" doesn't work...

**Comment by yum650350** [comment]
Thanks to pointing this out. 

Take a quick look for the width="100%" issue, the width prop should be number for method `getImageSizeFitWidth(source, width)`, but I think we can try something like 

`<ImageComponent onLayout={e=>setLayoutWidth(e.layout.width)} .../>`  

and use `getImageSizeFitWidth(source, layoutWidth)`

**Comment by vivaxy** [comment]
Thanks @sa1dai and @yum650350. `animated` attribute is not required since v3.1.2.
