### ISSUE TITLE
Support local images

### ISSUE THREAD

**Issue by timurridjanovic** [vivaxy/react-native-auto-height-image#8]
It would be nice if this component would support local images and not just remote image urls.

**Comment by vivaxy** [comment]
Local images are always loaded immediately. It'll be better if you use `<Image />` directly.

**Comment by timurridjanovic** [comment]
Image is a pain if I want auto height and just provide a width.

**Comment by ramonvermeulen** [comment]
+1 on this, I would also appreciate it if it would support local images.

**Comment by crystalloo** [comment]
@vivaxy I would also appreciate it if there's support for local image since using <Image/> to render local image still need you to set a height and width. Sometimes it's not necessarily the loading speed issue. But big thanks on this!

**Comment by crystalloo** [comment]
I found that it will actually load the local image if `imageURL` prop is provided a value:

```
 <AutoHeightImage
    width={width - 20}
    source={require('./local-image.jpg')}
    imageURL='http://ww4.sinaimg.cn/large/628d024fgw1f5p26qncvxj20le0u0go8.jpg'
/>
```

but if `imageURL` is left empty, it won't show anything.

**Comment by tombailey** [comment]
You can use https://github.com/vivaxy/react-native-auto-height-image/pull/12 for this

**Comment by vivaxy** [comment]
Resolved by https://github.com/vivaxy/react-native-auto-height-image/pull/12
